// src/data/colecciones.ts
import { Coleccion } from "./tipos";

export const COLECCIONES_DATA: Coleccion[] = [
  {
    id: 1,
    name: "Café Allure",
    price: 85000,
    image: "/cafe_allure.webp",
    description:
      "Una armonía perfecta de tonos café y nudes otoñales. Diseñada para reflejar calidez, elegancia y sofisticación en tus manos.",
      stock: 2,
    category: "colecciones",
    quantity: "3 Esmaltes",
    includes: ["Naturale", "Chocolate Chic", "Brillo Profesional"],
    // ¡Eliminamos details!
  },

  {
    id: 2,
    name: "Spark Icon",
    price: 45000,
    discountPrice: 39990,
    image: "/spark_icon.webp",
    description:
      "El dúo icónico para quienes aman destacar. Combina un color sólido de alta cobertura con destellos de glitter premium.",
      stock: 2,
    category: "colecciones",
    quantity: "2 Esmaltes",
    includes: ["Angel Pink", "Barbie Shine"],
    // ¡Eliminamos details!
  },
];

/*

LAYAOUT -->

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 1. EL NAVBAR VA PRIMERO }
        <Navbar />

        {/* 2. EL CONTENIDO VA DESPUÉS }
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}


NAVBAR -->

"use client";

import React, { useState } from "react";
import { Search, ShoppingBag, Mail, Menu, X } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
// 1. Importamos usePathname de la navegación moderna de Next.js
import { usePathname } from "next/navigation";

// 2. Diccionario de rutas (Principio DRY para no repetir código HTML)
const NAV_LINKS = [
  { name: "Esmaltes de Uñas", href: "/esmaltes" },
  { name: "Base y Brillo de Uñas", href: "/brillo" },
  { name: "Lámparas UV/LED", href: "/lamparas" },
  { name: "Colecciones", href: "/colecciones" },
  { name: "Arma tu kit", href: "/kit" },
  { name: "Ofertas", href: "/ofertas", isSpecial: true }, // Etiqueta especial para pintarla de rojo
];

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false);
  // 3. Capturamos la URL actual en la que estamos navegando
  const pathname = usePathname();

  return (
    <header className="pt-4 w-full border-b border-gray-200 bg-white sticky top-0 z-50">
      
      {/* Fila Superior: Grid de 3 columnas (Sin cambios) }
      <div className="max-w-[1440px] mx-auto px-6 h-20 grid grid-cols-3 items-center">
        
        {/* 1. Izquierda: Logo e Iniciar Sesión }
        <div className="flex justify-start">
          <div className="flex flex-col items-start gap-4">
            <Link href="/" className="relative cursor-pointer transition-transform hover:scale-105 block">
              <Image
                src="/Logo_Elizee_6.webp" 
                alt="Elizze Logo" 
                width={145} 
                height={50}
                className="w-[145px] h-auto object-contain"
              />
            </Link>
            
            <button className="relative z-30 cursor-pointer text-[10px] font-bold uppercase tracking-[0.25em] text-gray-400 hover:text-black transition-all duration-300 pl-1 bg-transparent border-none outline-none focus:outline-none block group">
              <span className="cursor-pointer">Iniciar Sesión</span>
            </button>
          </div>
        </div>

        {/* 2. Centro: Buscador }
        <div className="flex justify-center mb-10">
          <div className="relative w-full max-w-md hidden sm:block">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-4 h-4" />
            <input 
              type="text" 
              placeholder="Buscar..." 
              className="w-full border border-black px-10 py-2 rounded-sm text-sm focus:ring-1 focus:ring-gray-400 outline-none"
            />
          </div>
        </div>

        {/* 3. Derecha: Contacto, Carrito y Botón Menú }
        <div className="flex justify-end items-center gap-4 md:gap-8">
          <div className="flex flex-col items-end gap-3">
            <button className="flex items-center gap-3 cursor-pointer group bg-transparent border-none focus:outline-none">
              <span className="text-[13px] font-bold uppercase tracking-widest text-black group-hover:text-gray-600 transition-colors">
                Carrito
              </span>
              <ShoppingBag className="w-5 h-5 text-black stroke-[1.5] group-hover:scale-110 transition-transform" />
            </button>

            <button className="hidden md:flex items-center gap-3 cursor-pointer group bg-transparent border-none focus:outline-none">
              <span className="text-[13px] font-bold uppercase tracking-widest text-black group-hover:text-gray-600 transition-colors">
                Contacto
              </span>
              <Mail className="w-5 h-5 text-black stroke-[1.5] group-hover:scale-110 transition-transform" />
            </button>
          </div>

          <button 
            className="md:hidden p-2 cursor-pointer bg-transparent border-none focus:outline-none"
            onClick={() => setIsOpen(!isOpen)}
          >
            {isOpen ? <X className="w-7 h-7 text-black" /> : <Menu className="w-7 h-7 text-black" />}
          </button>
        </div>
      </div>

      {/* Menú de Navegación }
      <nav className={`
        ${isOpen ? "flex" : "hidden"} 
        md:flex w-full bg-white transition-all duration-300 ease-in-out px-4
      `}>
        <ul className="
          flex flex-col items-center w-full py-6 gap-y-6
          md:flex-row md:flex-wrap md:justify-center md:gap-x-4 lg:gap-x-8 xl:gap-x-12 md:py-4
          text-[10px] lg:text-[11px] xl:text-[12px] font-medium uppercase tracking-widest
          border-t md:border-none max-w-[1440px] mx-auto
        ">
          
          {/* 4. Mapeamos nuestras rutas }
          {NAV_LINKS.map((link) => {
            // Verificamos si la ruta actual coincide con el href de este enlace
            const isActive = pathname === link.href;

            // Clases base que tienen todos
            const baseClasses = "cursor-pointer transition-all block underline-offset-4 decoration-1";
            
            // Si es un enlace normal (Esmaltes, Lámparas, etc.)
            const normalClasses = isActive 
              ? "text-black underline" // Estado Activo: Fijo negro y subrayado
              : "text-gray-800 hover:text-black hover:underline"; // Estado Normal
            
            // Si es el enlace especial de (Ofertas)
            const specialClasses = isActive
              ? "text-red-900 underline font-bold" // Estado Activo Ofertas
              : "text-red-700 font-bold hover:text-red-900 hover:underline"; // Estado Normal Ofertas

            return (
              <li key={link.href} className="whitespace-nowrap">
                <Link 
                  href={link.href} 
                  className={`${baseClasses} ${link.isSpecial ? specialClasses : normalClasses}`}
                  onClick={() => setIsOpen(false)}
                >
                  {link.name}
                </Link>
              </li>
            );
          })}

        </ul>
      </nav>
    </header>
  );
}

CARDETALLE -->

// src/components/CardDetalle.tsx
"use client";

import Image from "next/image";

interface CardDetalleProps {
  onClose: () => void;
  name: string;
  price: number;
  discountPrice?: number;
  image: string;
  description?: string;
  
  // Variables del sistema (Las que se usan para filtrar)
  line?: string;
  colorFamily?: string;
  finish?: string;
  size?: string;
  type?: string; 
  quantity?: string;
  
  // NUEVO: Agregamos la propiedad 'includes' para las colecciones
  includes?: string[];
  
  // Mantenemos el nombre original 'details' para tus especificaciones extras
  details?: Record<string, string>;
}

export default function CardDetalle({
  onClose,
  name,
  price,
  discountPrice,
  image,
  description,
  line,
  colorFamily,
  finish,
  size,
  type,
  quantity,
  includes, // Lo recibimos
  details,
}: CardDetalleProps) {

  const formatPrice = (amount: number) => {
    return amount.toLocaleString("es-CL");
  };

  // EL CEREBRO: Fusiona ambos mundos manteniendo el nombre 'details'
  const buildDetailsList = () => {
    const list = [];
    
    // Parte A: Agregamos las variables puras del sistema
    if (line) list.push({ label: "Línea", value: line });
    if (colorFamily) list.push({ label: "Color", value: colorFamily });
    if (finish) list.push({ label: "Acabado", value: finish });
    if (type) list.push({ label: "Tipo", value: type });
    if (size) list.push({ label: "Tamaño", value: size });
    if (quantity) list.push({ label: "Cantidad", value: quantity });

    // Parte B: Si la colección tiene un arreglo de 'includes', lo unimos con comas
    if (includes && includes.length > 0) {
      list.push({ label: "Incluye", value: includes.join(", ") });
    }

    // Parte C: Agregamos los detalles técnicos extras que vengan en el objeto
    if (details) {
      Object.entries(details).forEach(([key, value]) => {
        list.push({ label: key, value: value });
      });
    }

    return list;
  };

  const productDetails = buildDetailsList();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="bg-white rounded-3xl shadow-2xl max-w-5xl w-full overflow-hidden relative">

        {/* Botón cerrar }
        <button
          onClick={onClose}
          className="absolute top-4 right-4 z-20 text-3xl text-gray-500 hover:text-black transition cursor-pointer"
        >
          ×
        </button>

        <div className="grid md:grid-cols-2">
          {/* Imagen }
          <div className="relative h-[400px] md:h-[650px] bg-gray-100">
            <Image
              src={image}
              alt={name}
              fill
              className="object-cover"
            />
          </div>

          {/* Información }
          <div className="p-8 md:p-10 flex flex-col justify-center">
            <h2 className="text-3xl md:text-4xl font-bold uppercase tracking-widest mb-4">
              {name}
            </h2>

            {/* Precio }
            <div className="mb-6">
              {discountPrice ? (
                <div className="flex items-center gap-4">
                  <span className="text-gray-400 line-through text-lg">
                    ${formatPrice(price)}
                  </span>
                  <span className="text-2xl font-bold text-black">
                    ${formatPrice(discountPrice)}
                  </span>
                </div>
              ) : (
                <span className="text-2xl font-bold text-black">
                  ${formatPrice(price)}
                </span>
              )}
            </div>

            {/* Descripción }
            {description && (
              <p className="text-gray-600 leading-relaxed mb-8">
                {description}
              </p>
            )}

            {/* Características dinámicas fusionadas }
            {productDetails.length > 0 && (
              <div className="space-y-3 border-t border-gray-200 pt-6">
                <h3 className="text-xs uppercase tracking-[0.3em] font-bold text-gray-400 mb-4">
                  Detalles del producto
                </h3>

                {productDetails.map((detail, index) => (
                  <div
                    key={index}
                    className="flex justify-between gap-4 border-b border-gray-100 pb-2"
                  >
                    <span className="font-semibold text-gray-800">
                      {detail.label}
                    </span>
                    <span className="text-gray-600 text-right">
                      {detail.value}
                    </span>
                  </div>
                ))}
              </div>
            )}

            {/* Botón carrito }
            <button
              className="
                mt-10
                bg-black
                text-white
                py-4
                uppercase
                tracking-widest
                text-sm
                font-bold
                hover:bg-gray-800
                transition
                cursor-pointer
              "
            >
              Añadir al carrito
            </button>

          </div>
        </div>
      </div>
    </div>
  );
}

PRODUCTCARD -->

"use client";

import React, { useState } from "react";
import Image from "next/image";
import CardDetalle from "./CardDetalle";

interface ProductCardProps {
  name: string;
  price: number;
  discountPrice?: number;
  image: string;
  description?: string;

  // 1. Agregamos las variables puras opcionales
  line?: string;
  colorFamily?: string;
  finish?: string;
  size?: string;
  type?: string; 
  quantity?: string;
  
  // NUEVO: Agregamos el arreglo de productos incluidos para las colecciones
  includes?: string[];

  // 2. Mantenemos tu objeto details intacto
  details?: Record<string, string>;
}

export default function ProductCard({
  name,
  price,
  discountPrice,
  image,
  description,
  // Recibimos las variables
  line,
  colorFamily,
  finish,
  size,
  type,
  quantity,
  includes, // Lo recibimos
  details,
}: ProductCardProps) {

  console.log("DETAILS PRODUCTCARD:", details);

  const [isDetalleOpen, setIsDetalleOpen] = useState(false);

  // Le agregamos un pequeño seguro por si llega un valor indefinido
  const formatPrice = (amount?: number) => {
    if (amount === undefined || amount === null || isNaN(amount)) {
      return "0";
    }
    return amount.toLocaleString("es-CL");
  };

  return (
    <>
      <div className="flex flex-col">

        <div
          onClick={() => setIsDetalleOpen(true)}
          className="group relative aspect-[3/4] overflow-hidden bg-gray-50 mb-6 cursor-pointer rounded-2xl shadow-sm hover:shadow-md transition-shadow duration-500"
        >

          {discountPrice && (
            <div className="absolute top-3 left-3 z-10 bg-white px-3 py-1 text-[9px] uppercase tracking-widest font-bold rounded-sm">
              Oferta
            </div>
          )}

          <Image
            src={image}
            alt={name}
            fill
            className="object-cover group-hover:scale-105 transition-all duration-700"
          />

          <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-300 bg-black/90 text-white text-center text-[10px] uppercase font-bold tracking-widest">
            Ver detalle
          </div>

        </div>

        <div className="text-center">

          <h4 className="text-[13px] uppercase font-bold tracking-widest mb-2">
            {name}
          </h4>

          {discountPrice ? (
            <>
              <div className="line-through text-gray-400 text-xs">
                ${formatPrice(price)}
              </div>

              <div className="font-bold">
                ${formatPrice(discountPrice)}
              </div>
            </>
          ) : (
            <div className="font-bold">
              ${formatPrice(price)}
            </div>
          )}

        </div>
      </div>

      {isDetalleOpen && (
        <CardDetalle
          onClose={() => setIsDetalleOpen(false)}
          name={name}
          price={price}
          discountPrice={discountPrice}
          image={image}
          description={description}
          // Le pasamos TODO el "Mix" al componente final
          line={line}
          colorFamily={colorFamily}
          finish={finish}
          size={size}
          type={type}
          quantity={quantity}
          includes={includes} // Lo pasamos
          details={details}
        />
      )}
    </>
  );
}
*/